import codingMonkeys from "../assets/codingmonkeys.jpg";

import { ArticleData } from "../types";

export const codingMonkeysContent: ArticleData = {
  headerData: {
    h1: "Coding Monkeys",
    h2: "Are You a Coding Monkey? Why This Is a Problem in the Age of AI",
    img: codingMonkeys,
    p1: `We can say a Coding Monkey is someone capable of writing and executing software without truly understanding the problem 
    that is solving. This probably was enough up to now but the code can be generated by AI tools. 
    If you’re just translating requirements into code without critical thinking, you might be at risk of being replaced.`,
  },
};
