import codingMonkeys from "../assets/codingmonkeys.jpg";
import monkeydriving from "../assets/monkeydriving.gif";

const CodingMonkeys = () => (
  <article className="blog-article">
    <h1 className="blog-article-h1">Coding Monkeys</h1>

    <h2 className="blog-article-h2">
      Are You a Coding Monkey? Why This Is a Problem in the Age of AI
    </h2>
    <img
      src={codingMonkeys}
      alt="coding-monkeys"
      className="blog-article-img"
    />

    <p className="blog-article-p">
      We can say a <strong>"Coding Monkey"</strong> is someone capable of
      writing and executing software without truly understanding the problem
      that is solving. This probably was enough up to now but the code can be
      generated by AI tools. If you’re just translating requirements into code
      without critical thinking, you might be at risk of being replaced.
    </p>

    <h4 className="blog-article-h4">AI Can Generate Code</h4>
    <p className="blog-article-p">
      AI can now write boilerplate code faster than any human. If your job is
      just to type code without deep understanding, AI can easily replace that
      function.
    </p>

    <h4 className="blog-article-h4">Lack of Problem-Solving Skills</h4>
    <p className="blog-article-p">
      Real programmers are problem solvers. AI is a tool to make the
      implementations easier but humans must define problems, think critically,
      and design solutions.
    </p>

    <h4 className="blog-article-h4">AI Needs Supervision</h4>
    <p className="blog-article-p">
      AI-generated code is not efficient, vulnerable and with logical errors. A
      "coding monkey" might accept AI suggestions leading to serious issues.
    </p>

    <h4 className="blog-article-h4">The Industry Needs Thinkers, Not Coders</h4>
    <p className="blog-article-p">
      Software Engineering is about designing scalable, maintainable, and
      efficient systems. Writing code is just a small part of the bigger
      picture.
    </p>

    <h2 className="blog-article-h2">Conclusion</h2>
    <p className="blog-article-p">Don't be a coding Monkey.</p>

    <img
      src={monkeydriving}
      alt="monkey-driving"
      className="blog-article-img"
    />
  </article>
);

export default CodingMonkeys;
